// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "baseURL": string;
      "apiKey": string;
      "model": string;
      "azureEndpoint": string;
      "azureDeployment": string;
      "azureApiVersion": string;
      "tagPolicy": string;
      "applyMode": string;
      "customTagList": string;
      "maxSuggestedTags": number;
      "temperature": string;
      "maxTokens": number;
      "tagColumnBackgroundColor": string;
      "tagColumnTextColor": string;
      "maxConcurrency": number;
      "minRequestIntervalMs": number;
      "maxRetries": number;
      "prompt": string;
    };
  }
}
